= Lab 6: Comprehensive Review

In lab six, we will apply everything we have learned and use the available
http://docs.ansible.com/ansible/latest/modules/list_of_cloud_modules.html#openstack[Ansible OpenStack modules]
to accomplish the following tasks:

* Creation of a private network using `os_network` module
* Creation of a private subnet to associate to the private network using the `os_subnet` module. Use CIDR 192.168.0.1/24
* Creation of a router to associate with the private network using the `os_router` module
* Create an OpenStack keypair using the public key on the localhost
* Updating the default security group to allow `icmp` (ping) and `ssh` access via port 22.
* Creation of an OpenStack instance using the `os_instance` module
* Updating quotas to the OpenStack project `os_quota` 

NOTE: A public network has already been created for you. 

____

HINT: Register the value of the private subnet in order to pass the OpenStack
subnet ID to the OpenStack router. 
____

When using any of the modules make sure to use the _mycloud_ as the value
for the _cloud_ argument. The _mycloud_ is the name of the cloud with the
authentication credentials provided within the _cloud.yml_ file located in
_/etc/openstack_.

Assignment: Attempt to create a _playbook.yml_ file that accomplishes all the 
task bullets. Ensure to take advantage of the Ansible documentation for clues
on how to complete each task and also via command-line make use of the `ansible-doc`
command for examples.

Example of using `ansible-doc`:

----
$ ansible-doc os_network
----

The above command would provide documentation on how to use the OpenStack
`os_network` module.


Answer to the following exercise:

----

---
- name: Lab 6 OpenStack Comprehensive Review
  hosts: localhost
  vars: 
    flavor: m1.small
    key_name: demokp
    server_name: student01
    image: cirros01
    
  tasks:

    - name: Get Cirros File
      get_url:
        url: http://download.cirros-cloud.net/0.4.0/cirros-0.4.0-x86_64-disk.img
        dest: /root/openstack-ansible/cirros
    
    - name: Upload Image.
      os_image:
        cloud: mycloud
        name: "{{ image }}"
        container_format: bare
        disk_format: qcow2
        state: present
        filename: cirros
        kernel: cirros-vmlinuz
        ramdisk: cirros-initrd
        properties:
          cpu_arch: x86_64
          distro: ubuntu
    
    - name: Create a private network named student01_private_network using os_network
      os_network:
        cloud: mycloud
        state: present
        name: student01_private_network

    - name: Create a private subnet named student01_private_subnet using os_subnet with CIDR 192.168.0.0/24
      os_subnet:
        cloud: mycloud
        state: present
        network_name: student01_private_network
        name: student01_private_subnet
        cidr: 192.168.0.1/24
      register: subnet

    - name: Create a router named studentX_router1.
      os_router:
        cloud: mycloud
        state: present
        name: student01_router1
        
    - name: Update default security group to allow ICMP traffic
      os_security_group_rule:
        cloud: mycloud
        state: present
        security_group: default
        protocol: icmp
        remote_ip_prefix: 0.0.0.0/0

    - name: Update default security group to allow SSH traffic
      os_security_group_rule:
        cloud: mycloud
        state: present
        security_group: default
        protocol: tcp
        port_range_min: 22
        port_range_max: 22
        remote_ip_prefix: 0.0.0.0/0

    - name: Update project's quota
      os_quota: 
        cloud: admin
        name: demo
        cores: 4
        instances: 2
         
    - name: Create an OSP Keypair using public key
      os_keypair:
        cloud: mycloud
        state: present
        name: "{{ key_name }}"
        public_key_file: "{{ ansible_user_dir }}/.ssh/id_rsa.pub"

    - name: Launch an OpenStack instance
      os_server: 
        cloud: mycloud
        state: present
        name: "{{ server_name }}"
        flavor: "{{ flavor }}"
        image: "{{ image }}"
        key_name: "{{ key_name }}"
        security_groups: default
        network: private

...
----

Now, let's verify that what we did is indeed working. In order to do this, we are going to use shade in a playbook. You could also login to cloud.example.com and use openstack commands to verify that everything is working. Here is an example for the image, network and subnet facts. 

----
---
- name: Lab 6 OpenStack Comprehensive Review - Check
  hosts: localhost
  vars: 
    flavor: m1.small
    key_name: demokp
    server_name: student01
    image: cirros01

  tasks:

    - name: Get image facts
      os_image_facts:
        cloud: mycloud
        image: "{{ image }}"

    - name: Show  image facts
      debug:
        var: openstack_image

    - name: Get network facts
      os_networks_facts:
        cloud: mycloud
        name: student01_private_network

    - name: Show network facts
      debug:
        var: openstack_networks

    - name: Get subnet facts
      os_subnets_facts:
        cloud: mycloud
        name: student01_private_subnet

    - name: Show network facts
      debug:
        var: openstack_subnets
...
----

Now, add the needed tasks to show the instance created facts. 

For more information on the Ansible OpenStack module, you could visit: https://docs.ansible.com/ansible/2.5/modules/list_of_cloud_modules.html#openstack

