toc::[]
= Overview of the Lab

== Abstract

_As OpenStack popularity and complexity continue to rise and new feature sets 
are introduced regularly, findings ways to simplify and produce consistent 
results is always at the forefront of any system administrator’s mind. With the 
use of Ansible, an agentless IT automation technology, a system administrator 
can do just that._

_The goal of this lab is to provide a brief introduction to Ansible, the 
usability of Ansible playbooks, and then show how to leverage key Ansible 
modules to better manage and simplify OpenStack environments. These management 
playbooks will consist of typical administrative tasks such as:_

* _Managing Networks_
* _Managing Instances_
* _Managing Resources_

_This lab is best suited for system and OpenStack administrators looking for 
ways to automate their day-to-day OpenStack administrative tasks._


== Environment Overview

This lab will provide a step-by-step on using several http://docs.ansible.com/ansible/latest/modules/list_of_cloud_modules.html#openstack[Ansible OpenStack modules] 
to manage everyday tasks. 
The lab environment consists of a two virtual machines running on 
Ravello. One acting as the workstation and ansible controllers and the other as a OpenStack All-in-one cloud. 

Each student's cloud instance consists of Red Hat OpenStack Platform `packstack` installation 
on Red Hat Enterprise Linux. 

== Lab Scope

The lab exercises are intended to be small simple playbooks that effect different
areas of day-to-day OpenStack administration. Each exercise will focus on a key
element of OpenStack, i.e. network creation. Each lab
builds upon the previous lab exercise and the lab will focus on 
using as many Ansible OpenStack modules whenever possible. The final lab exercise
will encapsulate all the information you have learned from the previous labs and
provide an opportunity to test your knowledge of managing OpenStack networks, 
instances and their resources. 

== Connectivity Details

The labs require students to be able to deploy the environment from OpenTLC and access the workstation instance via an `ssh` session. 
